[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
kotest = "5.9.1"
kotlinxSerialization = "1.8.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.11.0"
kotlin = "2.3.10"
kover = "0.9.6"
qodana = "2025.3.1"
kotlinxSerializationPlugin = "2.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
kotestRunner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotestAssertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotestProperty = { group = "io.kotest", name = "kotest-property", version.ref = "kotest" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerializationPlugin" }
